import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Navbar from "./ui/navbar/navbar";
import Footer from "./ui/footer/footer"
import { inter, poppins } from '@/app/ui/fonts';
import Navnew from "./ui/navbar/navnew";
import Navigation from "./ui/navbar/navigation";
import FooterNew from "./ui/footer/footerNew";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
      {/* <Navbar></Navbar> */}
      {/* <Navnew></Navnew> */}
      <Navigation></Navigation>
   
        {/* <header>

        </header> */}

        {/* <div className="test">
        {children}

        </div> */}
        {children}


        {/* <footer>
        <Footer></Footer>
        </footer> */}

        <FooterNew></FooterNew>
      </body>
    </html>
  );
}
