import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Navbar from "./ui/navbar/navbar";
import Footer from "./ui/footer/footer"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar></Navbar>
        </header>

        <div className="test">

        {children}
        </div>


        <footer>
        <Footer></Footer>
        </footer>

      </body>
    </html>
  );
}
